# Generated by Django 6.0.4 on 2026-05-07 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0005_alter_exam_unique_together_alter_exam_niveau_and_more'),
        ('matieres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('effectif', models.IntegerField(default=0)),
                ('niveau', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.specialite')),
            ],
        ),
        migrations.CreateModel(
            name='RepartitionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectif', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repartitions', to='exams.exam')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repartitions', to='groupes.groupeetudiant')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repartitions', to='exams.salle')),
            ],
            options={
                'unique_together': {('examen', 'groupe', 'salle')},
            },
        ),
        migrations.CreateModel(
            name='RepartitionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_number', models.IntegerField()),
                ('seat_code', models.CharField(max_length=10)),
                ('student_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('repartition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='groupes.repartitionexamen')),
            ],
            options={
                'ordering': ['repartition', 'place_number'],
            },
        ),
    ]
