# Generated by Django 6.0.4 on 2026-04-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_salle_exam_teacher_exam_salle'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='type',
            field=models.CharField(choices=[('salle', 'Salle'), ('amphi', 'Amphi')], default='salle', max_length=10),
        ),
    ]
