# Generated by Django 6.0.4 on 2026-05-03 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_niveau_exam_semestre_exam_specialite_and_more'),
        ('matieres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='niveau',
            field=models.CharField(blank=True, choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=10, null=True, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='semestre',
            field=models.IntegerField(blank=True, choices=[(1, 'Semestre 1'), (2, 'Semestre 2')], null=True, verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matieres.specialite', verbose_name='Spécialité'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
