# Generated by Django 6.0.4 on 2026-05-08 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matieres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultatMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('principale', 'Principale'), ('rattrapage', 'Rattrapage')], default='principale', max_length=20)),
                ('oral', models.FloatField(default=0)),
                ('ds', models.FloatField(default=0)),
                ('exam', models.FloatField(default=0)),
                ('tp', models.FloatField(default=0)),
                ('moyenne', models.FloatField(default=0)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matieres.matiere')),
            ],
        ),
    ]
