# Generated by Django 6.0.4 on 2026-05-09 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0001_initial'),
        ('resultats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultatmatiere',
            options={'ordering': ['matiere__semestre', 'matiere__code']},
        ),
        migrations.AddField(
            model_name='resultatmatiere',
            name='exam_r',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resultatmatiere',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resultatmatiere',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resultatmatiere',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='matieres.matiere'),
        ),
        migrations.AlterField(
            model_name='resultatmatiere',
            name='session',
            field=models.CharField(choices=[('principale', 'Session Principale'), ('rattrapage', 'Session Rattrapage')], default='principale', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='resultatmatiere',
            unique_together={('etudiant', 'matiere', 'session')},
        ),
    ]
