# Generated by Django 6.0.4 on 2026-05-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultats', '0002_alter_resultatmatiere_options_resultatmatiere_exam_r_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultatmatiere',
            name='moyenne_finale',
            field=models.FloatField(default=0),
        ),
    ]
