# Generated by Django 6.0.4 on 2026-04-27 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('credits', models.IntegerField(default=3)),
                ('coefficient', models.IntegerField(default=1)),
                ('nature', models.CharField(choices=[('MX', 'Matière de Base'), ('CC', 'Contrôle Continu'), ('TP', 'Travaux Pratiques'), ('TD', 'Travaux Dirigés')], default='MX', max_length=2)),
                ('semestre', models.IntegerField(blank=True, choices=[(1, 'Semestre 1'), (2, 'Semestre 2'), (3, 'Semestre 3'), (4, 'Semestre 4'), (5, 'Semestre 5'), (6, 'Semestre 6')], null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(blank=True, limit_choices_to={'role': 'enseignant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres_enseignees', to=settings.AUTH_USER_MODEL)),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='matieres.specialite')),
            ],
            options={
                'ordering': ['specialite', 'semestre', 'code'],
            },
        ),
    ]
