# Generated by Django 6.0.4 on 2026-05-09 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0001_initial'),
        ('users', '0004_department_remove_studentprofile_filiere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialite',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialites', to='users.department'),
        ),
    ]
