# Generated by Django 6.0.4 on 2026-05-09 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0002_specialite_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matiere',
            options={'ordering': ['specialite', 'niveau', 'semestre', 'code'], 'verbose_name': 'Matière', 'verbose_name_plural': 'Matières'},
        ),
        migrations.AlterModelOptions(
            name='specialite',
            options={'ordering': ['code'], 'verbose_name': 'Spécialité', 'verbose_name_plural': 'Spécialités'},
        ),
        migrations.AddField(
            model_name='matiere',
            name='niveau',
            field=models.IntegerField(choices=[(1, 'Niveau 1 (L1)'), (2, 'Niveau 2 (L2)'), (3, 'Niveau 3 (L3)')], default=1, help_text="Niveau d'étude auquel cette matière est enseignée"),
        ),
        migrations.AddField(
            model_name='matiere',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='coefficient',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='credits',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='semestre',
            field=models.IntegerField(blank=True, choices=[(1, 'Semestre 1'), (2, 'Semestre 2'), (3, 'Semestre 3'), (4, 'Semestre 4'), (5, 'Semestre 5'), (6, 'Semestre 6')], help_text='Semestre spécifique dans le niveau', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('code', 'specialite', 'niveau')},
        ),
    ]
