# Generated by Django 6.0.4 on 2026-04-28 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_studentprofile_user_alter_teacherprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='niveau',
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('1', 'Niveau 1'), ('2', 'Niveau 2'), ('3', 'Niveau 3'), ('4', 'Niveau 4'), ('5', 'Niveau 5')], max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='users.department')),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.groupe'),
        ),
    ]
